version: '3.8'

services:
  web_api:
    image: callumhoughton22/mushroom-api:latest
    command: gunicorn --bind 0.0.0.0:5000 manage:APP
    restart: unless-stopped
    volumes:
      - static_volume:/app/files
    expose:
      - 5000
    env_file:
      - ./.docker.env
    environment:
      - FLASK_ENV=production

  front_end:
    image: callumhoughton22/mushroom-classification-front-end:latest
    volumes: 
      - front_end_vol:/app/build
    ports:
      - 8000:5000

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - static_volume:/app/files
      - front_end_vol:/var/www/mushroomUI
      - ./data/certbot/www:/var/www/certbot
      - /etc/letsencrypt/:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - front_end
      - web_api
      - certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

volumes:
  static_volume:
  front_end_vol:
