version: '3.8'

services:
  web:
    image: callumhoughton22/mushroom-api:latest
    command: python manage.py run -h 0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - ./.docker.env
    environment:
      - FLASK_ENV=development

  front-end:
    build: ./frontend
    ports:
      - 8000:5000
